### ISSUE TITLE
Multi-Signature Wallet Application

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#1]
This issue is meant to document the various sub tasks that are required in order to create a fully functional multi-signature wallet written in Sway.

There are various components and they are grouped into categories.

**The Basics**

- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7

**Ethereum Signature Capability**

- [x] #10
- [x] #11
- [x] #12

**Frontend**

- [ ] #18

**Contract Calls**

- [x] #22

**Documentation**

- [x] #23
- [x] #24

**Comment by bitzoic** [comment]
Closing in favor of https://github.com/FuelLabs/sway-applications/issues/18
