### ISSUE TITLE
Implement function execution for the DAO application

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/sway-applications#105]
### Motivation

Currently we are passing a dummy function selector and function data to the dao voting contract.  We would like to make sure the low level assembly in the function actually works as intended.

**Comment by matt-user** [comment]
This is currently blocked by FuelLabs/sway#1261

**Comment by matt-user** [comment]
So the above blocker doesn't actually solve the arbitrary abi call issue, which needs to be discussed more.  In the meantime we will execute an abi known at compile time by the contract.  This limits the DAOs functionality, but is helpful for demonstrating the dao works.

**Comment by matt-user** [comment]
Once [this](https://github.com/FuelLabs/sway/pull/3626) is merged it should unblock this issue

**Comment by simonr0204** [comment]
> Once [this](https://github.com/FuelLabs/sway/pull/3626) is merged it should unblock this issue

For functions with only one argument, yes.

**Comment by simonr0204** [comment]
This is now unblocked.

**Comment by bitzoic** [comment]
This issue has been resolved
