### ISSUE TITLE
Potential overflow in execute when calculating approval percentage 

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/sway-applications#106]
### Describe the bug

If the number of yes votes is large enough then multiplying them by 100, to calculate the approval percentage, will cause an overflow.

### Steps to reproduce

Place 2^64 yes votes on a proposal and then try to execute it.

### Minimal reproducible code example

```Rust
let (gov_token, gov_token_id, deployer, user, asset_amount) = setup().await;
            deployer
                .dao_voting
                .constructor(gov_token_id)
                .call()
                .await
                .unwrap();

            assert!(
                deployer
                    .gov_token
                    .unwrap()
                    .mint_and_send_to_address(2^64, user.wallet.address())
                    .append_variable_outputs(1)
                    .call()
                    .await
                    .unwrap()
                    .value
            );

            let tx_params = TxParameters::new(None, Some(1_000_000), None, None);
            let call_params = CallParameters::new(
                Some(asset_amount),
                Some(AssetId::from(*gov_token_id)),
                Some(100_000),
            );
            assert!(
                user.dao_voting
                    .deposit()
                    .tx_params(tx_params)
                    .call_params(call_params)
                    .call()
                    .await
                    .unwrap()
                    .value
            );

            let call_data = get_call_data(user.wallet.address(), gov_token_id);

            assert!(
                user.dao_voting
                    .add_proposal(1, 10, call_data.clone())
                    .call()
                    .await
                    .unwrap()
                    .value
            );

            assert!(
                user.dao_voting
                    .vote(0, 2^64, true)
                    .call()
                    .await
                    .unwrap()
                    .value
            );
```

### Rust Version

1.61.0

### Forc Version

0.16.1

### Expected behavior

Ideally there should be no overflow in this scenario.

**Comment by Braqzen** [comment]
You can divide the max size for your chosen integer by 100 and then compare it with your chosen value. Revert if overflow.

**Comment by matt-user** [comment]
Do you mean restrict the value `proposal.yes_votes` and `proposal.no_votes` to be less than 100 times the max `u64` value?  That would work and would definitely be a better solution than just reverting in the execute function.

**Comment by Braqzen** [comment]
> Do you mean restrict the value `proposal.yes_votes` and `proposal.no_votes` to be less than 100 times the max `u64` value? That would work and would definitely be a better solution than just reverting in the execute function.

I'm currently reviewing your PR so I don't know what the code does yet. 
`u64` is massive so anything getting close to that is more of design flaw from the dev. You probably do not need to handle it explicitly. I would (without seeing the code yet) do what I have said above.

**Comment by adlerjohn** [comment]
> so anything getting close to that is more of design flaw from the dev

Actually, you'd be surprised 😂. It's only a billion-billion. With 9 decimals for tokens, that only leaves about a billion.

**Comment by simonr0204** [comment]
@matt-user  just doing some housekeeping. It's been 6 months - I presume this is either resolved or stale ? Will let you close accordingly.

**Comment by matt-user** [comment]
> @matt-user just doing some housekeeping. I presume this is either resolved or stale ? Will let you close accordingly.

Yeah I never ended up fixing this.  I meant to solve this after I figured out how to handle arbitrary contract calls... but that ended up not happening.  In fact, I think the dao still cannot execute proposals, but that's another topic.  It might be best to close this issue and only track #154 .
