### ISSUE TITLE
TicTacToe Game

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#107]
### Application Description

Tic-tac-toe, noughts and crosses, or Xs and Os is a paper-and-pencil game for two players who take turns marking the spaces in a three-by-three grid with X or O. The player who succeeds in placing three of their marks in a horizontal, vertical, or diagonal row is the winner.

[Citation](https://en.wikipedia.org/wiki/Tic-tac-toe)

This is a simple game that should be placed in `sway-applications/games/TicTacToe/`
The structure of the project should be something akin to

```
TicTacToe/
├── contract
|    └── Files related to smart contract
├── user-interface
|    └── Files related to UI
├── README.md
└── SPECIFICATION.md
```

### Features

- [x] #109
- [ ] #110
- [x] #111

**Comment by bitzoic** [comment]
Closing in favor of https://github.com/FuelLabs/sway-applications/issues/110
