### ISSUE TITLE
EIP-191 signature support

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#11]
Support payloads (signatures) constructed from Metamask, Trezor & Ledger.

**Comment by adlerjohn** [comment]
I don't think separate issues are needed for this. What's really needed is simply [EIP-191](https://eips.ethereum.org/EIPS/eip-191) signature support, not specifically supporting different wallets.

**Comment by K1-R1** [comment]
Closed as of https://github.com/FuelLabs/sway-applications/pull/272
