### ISSUE TITLE
Flash Loan Smart Contract

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway-applications#115]
### Motivation

# Summary

A flash loan is a special kind of loan that does not require any collateral. It is received and paid back in a single transaction with a small fee.

# Rough Smart Contract Design

- There should be a LendingPool Contract which a loan can be taken from. This should reflect the exchange contract found in the SwaySway app.
- There should be a minting contract where tokens can be minted for a flash loan.
- There should be a Flash Loan contract that recieves a loan
    - There should be a function that starts flash loan
    - There should be a function gets called by the lending pool to execute the loan
        - This function will not execute anything for now
    - Should be able to change where the loan is originating 
- Events should be emitted when
    - A flash loan is completed

**Comment by bitzoic** [comment]
> Can you update this to follow the "New Application" structure? It's not exactly a new feature but more of an entire app - or at least the start of the basis for it.

As this is just the contract, wouldn't this be a feature? I can make a separate issue for the flash loan application and have it track this.

**Comment by Braqzen** [comment]
> > Can you update this to follow the "New Application" structure? It's not exactly a new feature but more of an entire app - or at least the start of the basis for it.
> 
> As this is just the contract, wouldn't this be a feature? I can make a separate issue for the flash loan application and have it track this.

Well, everything else in this repo is basically just a smart contract but they are being slowly built towards usage within applications.

> I can make a separate issue for the flash loan application and have it track this.

Sure, that sounds good too

**Comment by simonr0204** [comment]
On Fuel, flashloans can be implemented at the token level with no need for liquidity. This functionality will be added to the std-lib when the final blockers are removed, where a contract allowing flash minting of its asset will be demonstrated.

Given this understanding of flash loans, do we still want to build a standalone application for this, or could we showcase this within another application (e.g. flash swaps on the AMM) ?

**Comment by Braqzen** [comment]
> On Fuel, flashloans can be implemented at the token level with no need for liquidity. This functionality will be added to the std-lib when the final blockers are removed, where a contract allowing flash minting of its asset will be demonstrated.
> 
> Given this understanding of flash loans, do we still want to build a standalone application for this, or could we showcase this within another application (e.g. flash swaps on the AMM) ?

Having an integration into a larger system is nice although it may be more difficult to isolate the concept so that others can easily replicate it. If a flash-loan has a lot of different applications then it should be its own app so that people can easily refer to an MVP. If it's simple to implement then we may close this issue and leave it in the AMM and point people at that explicitly.

So:

```
if flash-loan == easy {
    AMM
} else if lots_of_utility {
    Separate Application
} else {
    // difficult app
    Separate Application
}
```

**Comment by simonr0204** [comment]
I think `flash-loan == easy` ... but we should know for sure soon! 

Given that on Fuel there are actually 2 flavours of flash-loan : liquidity-backed or flash-mint backed, we might want to do something to explicitly demonstrate that. The latter case is optional functionality for a token contract - and probably something we should consider adding to our Sway-side contract for bridged tokens.

**Comment by simonr0204** [comment]
Closing this and opening an issue for a Flashloan library.
