### ISSUE TITLE
Fractional NFT Application

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#129]
### Application Description

A fractional NFT is an NFT that has been "split up" (or fractionalized) into smaller pieces.
The NFT itself is not actually split however it is represented by a set number of tokens / native assets where each token / native asset costs a fraction of the NFT.

For example, if an NFT is worth "100" of some asset and the owner decides to split the NFT into 10 pieces then each piece is now worth "10" of that asset.
This allows for a smaller entry price into NFT ownership and allows for some interesting dynamics to be introduced such as lending / borrowing, staking, governance of the NFT... 

### Features

- [x] #132
- [x] #133
- [x] #134

**Comment by bitzoic** [comment]
Closing as this application has been deprecated
