### ISSUE TITLE
Name Registry Application

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#131]
### Application Description

Following on from Ethereum, which follows on from DNS, a name service application is one where a user is able to interact with some address that is in human readable form instead of the typical hash variation. 
For example, an address may take the form of `0x01234...` while a human readable form would be `alice.fuel`.

This allows a user to send funds to `alice.fuel` which is easier to remember and reduces the chance of making a mistake when writing out the address.

The application would allow a user to purchase a domain `alice.fuel` and allow them to expand the domain as they wish into many subdomains e.g. `blog.alice.fuel`, `store.alice.fuel` etc.
Furthermore, the domain would be tradeable with others since its representation is an NFT.

### Features

- [x] #137
- [ ] #138
- [x] #139

**Comment by adlerjohn** [comment]
Hmmm. "Ethereum Name Service" is the name of a product, but the actual _thing_ is a name registry. Would prefer this application be named boringly as a not-product, i.e. "name registry." Similar to "non-fungible token" and "auction."

**Comment by boray** [comment]
I've started to work on a name registry service for Fuel at the EthCC hackathon. I will post updates.

**Comment by bitzoic** [comment]
Closing to consolidate to just https://github.com/FuelLabs/sway-applications/issues/138
