### ISSUE TITLE
Oracle Node

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#165]
## Summary

The node should query some price feed e.g. BTC / USD and update the smart contract with the latest data.
It should use a freely available API so that anyone can run the node / sign up for an API key to use without being rate limited.

The node should be written in Rust so that it is blazingly fast.

**Comment by matt-user** [comment]
Off-Chain Oracle Nodes depend heavily on blockchain events to function (which are currently unimplemented).  See [here](https://docs.chain.link/docs/architecture-request-model/#off-chain-oracle-node) for more info.
