### ISSUE TITLE
DAO Documentation

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/sway-applications#175]
### Motivation

This application requires documentation to inform the user about the project.
This includes:

- README.md
    -  What the application is, how to run it etc
- SPECIFICATION.md
    - General overview of the application use cases, contract design, UI design etc
- Any additional informative files

**Comment by Braqzen** [comment]
No issue has currently addressed the UI aspect since there is no UI at this time. That being said there is sufficient documentation that has been added through other issues therefore this issue is being closed.
