### ISSUE TITLE
Finish testing the Fundraiser

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#219]
### Motivation

Recently the projects have been bumped to a newer SDK release which supports [block manipulation](https://fuellabs.github.io/fuels-rs/v0.23.0/testing/chains.html). There are a few tests that need to be completed.

Look in `harness.rs` to see if there is a note mentioning which tests must be updated otherwise look through all the functions.

**Comment by ef3n9r98** [comment]
Hi @Braqzen - same on this issue. Is there a budget for fixing this issue, and if so, how much? 

I know some jr. devs who'd love to gain some experience and I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!
