### ISSUE TITLE
Call contracts without knowing their ABI at compile time of the multisig

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#22]
Once a Tx has been approved past a threshold it should be executable.

In order to accomplish execution we need to be able to call arbitrary contracts without knowing anything about them at the compilation of the multi-signature wallet.
This means that we need to be able to make generic calls at runtime.

**Comment by simonr0204** [comment]
Blocked by
https://github.com/FuelLabs/sway/issues/3078
https://github.com/FuelLabs/fuels-rs/issues/723
https://github.com/FuelLabs/fuels-rs/issues/709
