### ISSUE TITLE
AMM: Swap exact input and swap exact output scripts

### ISSUE THREAD

**Issue by supiket** [FuelLabs/sway-applications#229]
#### Description

Swap exact input script that:
- Takes an asset route (i.e. a vector of asset IDs) and a vector of amounts as input
- Calls `swap_exact_input` function ([ABI and documentation](https://github.com/FuelLabs/sway-applications/blob/master/AMM/project/libraries/src/interface.sw#L108-L123), [implementation](https://github.com/FuelLabs/sway-applications/blob/master/AMM/project/contracts/exchange-contract/src/main.sw#L226-L260)) for each subsequent asset pair to perform potentially (i.e. if the route has more than two assets) multiple swaps in a row 
- Returns the bought amount of the last asset

Swap exact output script that:
- Takes an asset route (i.e. a vector of asset IDs) and a vector of amounts as input
- Calls `swap_exact_output` function ([ABI and documentation](https://github.com/FuelLabs/sway-applications/blob/master/AMM/project/libraries/src/interface.sw#L125-L143), [implementation](https://github.com/FuelLabs/sway-applications/blob/master/AMM/project/contracts/exchange-contract/src/main.sw#L262-L300)) for each subsequent asset pair to perform potentially (i.e. if the route has more than two assets) multiple swaps in a row 
- Returns the sold amount of first asset

#### Motivation

These scripts will allow swapping two assets that do not have a direct liquidity pool.

However, the frontend of the AMM app (#233) may use this script to perform any swap operation, e.g. even if two assets have a pool or the asset route consists of only two assets. Another use case of this script can be finding an optimal route while swapping one asset for another, whether the assets have a pool or not. These routes should be calculated in the frontend and passed to the script.

**Comment by Braqzen** [comment]
This sounds like a new feature which is a smart contract implementation.
I recommend looking at any app spec labelled "New Application" and replicating that in order to track the overall application port and then this could be a "New Feature" (not an improvement since an improvement is dependent on something existing and being able to improve it).
