### ISSUE TITLE
AMM Application

### ISSUE THREAD

**Issue by supiket** [FuelLabs/sway-applications#231]
### Application Description

Port [SwaySwap](https://github.com/FuelLabs/swayswap) that is an AMM-based DEX app into this repo.

### Features

- [x] #232
- [ ] #233
- [x] #234
- [x] #235 
- [x] #287 
- [x] #229

**Comment by simonr0204** [comment]
For this repo I was thinking maybe rename to something generic like `AMM` ?

**Comment by supiket** [comment]
> For this repo I was thinking maybe rename to something generic like `AMM` ?

It makes perfect sense for consistency.

**Comment by bitzoic** [comment]
Closing to consolidate to https://github.com/FuelLabs/sway-applications/issues/233
