### ISSUE TITLE
AMM User Interface: Support running Sway scripts in project

### ISSUE THREAD

**Issue by supiket** [FuelLabs/sway-applications#235]
AMM's scripts `swap-exact-input`, `swap-exact-output` and `atomic-add-liquidity` should be run when swapping or adding liquidity.

Awaiting https://github.com/FuelLabs/fuels-ts/issues/698

**Comment by bitzoic** [comment]
Closing in favor of https://github.com/FuelLabs/sway-applications/issues/233
