### ISSUE TITLE
Update the style guide for the contributing book

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#250]
### Motivation

Once the new sway book is released, [via this PR](https://github.com/FuelLabs/sway/pull/2562), the style guide in this repo should be updated to either reference the official book or if there are some distinctions that do not apply to the general book but apply here then they should be outlined.

This removes duplication and we can either refer to the book or refer to the book and comment on exceptions.

**Comment by simonr0204** [comment]
@Braqzen  bumping this issue as we now have the book and the reference.

However, the current guidelines don't actually mention the book, do they?

**Comment by Braqzen** [comment]
> @Braqzen bumping this issue as we now have the book and the reference.
> 
> However, the current guidelines don't actually mention the book, do they?

I'll check the issues and the contributing book and likely rewrite this issue to change the contributing book.
