### ISSUE TITLE
Oracle: Create `paths` module in test utilities

### ISSUE THREAD

**Issue by supiket** [FuelLabs/sway-applications#279]
### Motivation

Currently, there is a string literal path used in a utility function for tests, that is the [contract binary path](https://github.com/FuelLabs/sway-applications/blob/master/oracle/packages/utils/src/lib.rs#L37).

In order to make these paths easier to modify and improve the overall structure of the test file:
1. A new module in the [lib.rs](https://github.com/FuelLabs/sway-applications/blob/master/oracle/packages/utils/src/lib.rs) file named `paths` should be created.
2. Inside this module, a constant of type `&str` that follow the `SCREAMING_SNAKE_CASE` style should be assigned the relevant path.
3. The string literal linked above should be replaced by the newly created constant after proper importing.

Note: The path provided to [abigen!](https://github.com/FuelLabs/sway-applications/blob/master/oracle/tests/utils/mod.rs#L3) macro should remain [string literals](https://doc.rust-lang.org/reference/tokens.html#string-literals).

**Comment by brandonsurh** [comment]
Hello, while taking a look at this issue I noticed that the paths/links to the `mod.rs` file are no longer valid due to some sort of restructuring of the repository. Would you be able to specify which `mod.rs` file you are referring to?

**Comment by supiket** [comment]
> Hello, while taking a look at this issue I noticed that the paths/links to the `mod.rs` file are no longer valid due to some sort of restructuring of the repository. Would you be able to specify which `mod.rs` file you are referring to?

Sure, edited the description of the issue to reflect the changes in the structure of the Oracle app.

**Comment by supiket** [comment]
The issues closed by #298 were separated by a comma in the PR description, which resulted in closing only the first issue. Closing manually for this reason.
