### ISSUE TITLE
Missing `)` in documentation of OTC README

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#305]
### Motivation

There is an opening `(` but not a `)` at the end of the sentence in the attached image. The link to the section can be found [here](https://github.com/FuelLabs/sway-applications/tree/master/OTC-swap-predicate#predicates-in-fuel).

### Image 

![1](https://user-images.githubusercontent.com/103777923/204606260-45697d53-7908-462b-a14d-844f648d23ac.png)

**Comment by jives-mcgee** [comment]
Thank you for posting this on https://goodfirstissues.com. I will try to fix it, this is literally the first issue I've ever tried to fix on github.
