### ISSUE TITLE
Tests that revert with `#[should_panic(expected = "Revert(18446744073709486080)")]`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#330]
### Motivation

Here is a list of tests that need to be updated when appropriate changes are made to use the correct expected message.

- English Auction
  - `bid.rs`
    - `when_bidder_does_not_own_nft()`
    - `when_auction_contract_does_not_have_permission_to_transfer_nft()`
  - `create.rs`
    - `when_auction_not_approved_for_transfer()`

Since the application has been bumped the error message had to be changed. Those tests will have the `#[ignore]` annotation. It looks like they need to be set up as they don't seem to be correctly set up to hit the errors.

**Comment by supiket** [comment]
These can be updated once [feat: support logs from external contracts](https://github.com/FuelLabs/fuels-rs/pull/762) is merged.

**Comment by SwayStar123** [comment]
@bitzoic I dont see the above tests anymore. Is this issue still relevant?

**Comment by bitzoic** [comment]
Closing as these tests were related to the old design before multi native assets were introduced
