### ISSUE TITLE
Timelock Application

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#335]
### Application Description

A time-lock contract allows users to restrict the time-frame of when a transaction can be executed.
For example, a user may be able to perform a transfer; but, only if it's in the first week of each month.

This is accomplished by specifying transaction arguments in addition to the period in which the transaction may be executed. If the specified period is passed and the transaction has not been executed then it is permanently locked and can never be executed.

### Features

- [x] #336
- [ ] #337

**Comment by bitzoic** [comment]
Closing to consolidate to just https://github.com/FuelLabs/sway-applications/issues/337
