### ISSUE TITLE
Create an Application Template

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#341]
### Motivation

We have been creating applications from scratch or by copying another application and making updates to those files which results in certain sections being overlooked and not updated.

The purpose of a template application is to create a structure which can be copy and pasted reducing the workload.

The template will include 

- Documentation for `README.md` and `SPECIFICATION.md`
- `project/<contract>/src/`
- `project/<contract>/tests/`

**Comment by simonr0204** [comment]
Should `src` contain empty  `interface.sw`, `data_structures.sw`, and `errors.sw` libraries, with these things `dep`'d in `main.sw` ?

**Comment by Braqzen** [comment]
> Should `src` contain empty `interface.sw`, `data_structures.sw`, and `errors.sw` libraries, with these things `dep`'d in `main.sw` ?

1. I thought to create a template interface similar to the default provided by `forc`.
2. I thought that data structures should be a directory with a single library which is also linked in the main file so that users can see how to link via a directory and incentivize them to separate units of code into modules. In the end it all gets linked together so it's better to keep things separate. It sets things up for larger projects
3. errors, events and utils files can also be added and linked via `dep`

As for the tests I'm planning on creating a structure similar to #318 / #338 . It will likely also be linked but empty

**Comment by K1-R1** [comment]
> As for the tests I'm planning on creating a structure similar to #322 / #338 . It will likely also be linked but empty

Would this mean having `tests/functions` contain empty `core` and `info` directories by default?

**Comment by Braqzen** [comment]
> > As for the tests I'm planning on creating a structure similar to #322 / #338 . It will likely also be linked but empty
> 
> Would this mean having `tests/functions` contain empty `core` and `info` directories by default?

I am uncertain about that structure or rather the distinction being made. I'm happy with a concept of `core`, whatever that is, and then any number of different concepts such as getters being the `info` or some other concept being a different directory / abi. I thought that for now it's probably a good way to go, or at least it's better than having all functions in 1 directory.

**Comment by supiket** [comment]
> 2. I thought that data structures should be a directory with a single library which is also linked in the main file so that users can see how to link via a directory and incentivize them to separate units of code into modules. In the end it all gets linked together so it's better to keep things separate. It sets things up for larger projects

I think this would be great. There were instances of users having a single `src` that has `data_structures.sw`, `interface.sw` etc. and a contract entry point `main.sw`. This structure makes it impossible to access any data structure or the ABI to either implement it or call functions of it from other projects.

**Comment by Braqzen** [comment]
> > 2. I thought that data structures should be a directory with a single library which is also linked in the main file so that users can see how to link via a directory and incentivize them to separate units of code into modules. In the end it all gets linked together so it's better to keep things separate. It sets things up for larger projects
> 
> I think this would be great. There were instances of users having a single `src` that has `data_structures.sw`, `interface.sw` etc. and a contract entry point `main.sw`. This structure makes it impossible to access any data structure or the ABI to either implement it or call functions of it from other projects.

I meant that `data_structures.sw` would become a directory in the same place as the file. This would not solve the issue which you have outlined. External libraries are documented in the book(s) so a user can use them if they want, as for us, it sets up a structure for a self contained application rather than a coupled one. I think iff there is a time where we need to expand an application to utilize common code then we can do that otherwise this belongs more towards the sway library repo rather than how we have currently been developing applications.

**Comment by simonr0204** [comment]
Our current layout doesn't have `data_structures` as a directory though, right? I was thinking the template would just replicate basically [this](https://github.com/FuelLabs/sway-applications/tree/master/DAO/project/DAO-contract/src)

**Comment by Braqzen** [comment]
> Our current layout doesn't have `data_structures` as a directory though, right? I was thinking the template would just replicate basically [this](https://github.com/FuelLabs/sway-applications/tree/master/DAO/project/DAO-contract/src)

The [English Auction](https://github.com/FuelLabs/sway-applications/tree/master/auctions/english-auction/project/auction-contract/src/data_structures) does this and I believe there either is another app that does this or there is / are PRs that also add this structure

**Comment by simonr0204** [comment]
Oh, right you are!
