### ISSUE TITLE
AMM/exchange-contract. Internal compiler error: Verification failed: Type mismatch found for call to 'log_373'

### ISSUE THREAD

**Issue by zoey-t** [FuelLabs/sway-applications#350]
### Describe the bug

I am compiling the AMM in the sway applications. 
i got the following error
```
Internal compiler error: Verification failed: Type mismatch found for call to 'log_373'.
Please file an issue on the repository and include the code that triggered this error.
```

No issues when building other contracts/libraries. This issue only happens when compiling the [exchange-contract](https://github.com/FuelLabs/sway-applications/tree/028770f7b92364df92b28358cd83caa4fbc5d8e3/AMM/project/contracts/exchange-contract).

### Steps to reproduce

1. `cd cd AMM/project/contracts/exchange-contract `
2. `forc build`

### Minimal reproducible code example

```Rust
None
```

### Rust Version

rustc 1.66.0 (69f9c33d7 2022-12-12)

### Forc Version

forc 0.33.0

### Expected behavior

forc build successfully

**Comment by zoey-t** [comment]
similar error for airdrop. `Type mismatch found for call to 'log_121'`

**Comment by Braqzen** [comment]
> similar error for
> 
> 1. airdrop. `Type mismatch found for call to 'log_121'`
> 2. DAO.  ` Type mismatch found for call to 'log_99'`
> 3. fractional-NFT-contract `Type mismatch found for call to 'log_67'`
> 4. NFT-contract. `Type mismatch found for call to 'log_378'`

The repository uses a different version which is stated in the [README](https://github.com/FuelLabs/sway-applications#running-a-project).

![1](https://user-images.githubusercontent.com/103777923/212775300-3483c09c-84da-4aab-b357-7f17de7dc596.png)

Could you upgrade to the stated versions and let us know if the issues persists? I have not had this issue.

**Comment by Braqzen** [comment]
cc @mohammadfawaz for a possible ICE

**Comment by zoey-t** [comment]
> > similar error for
> > 
> > 1. airdrop. `Type mismatch found for call to 'log_121'`
> > 2. DAO.  ` Type mismatch found for call to 'log_99'`
> > 3. fractional-NFT-contract `Type mismatch found for call to 'log_67'`
> > 4. NFT-contract. `Type mismatch found for call to 'log_378'`
> 
> The repository uses a different version which is stated in the [README](https://github.com/FuelLabs/sway-applications#running-a-project).
> 
> ![1](https://user-images.githubusercontent.com/103777923/212775300-3483c09c-84da-4aab-b357-7f17de7dc596.png)
> 
> Could you upgrade to the stated versions and let us know if the issues persists? I have not had this issue.

it works with 0.32.2

**Comment by Braqzen** [comment]
Closing since it works with the correct version.

**Comment by mohammadfawaz** [comment]
So there's an issue with `forc 0.33.0` but not with `forc 0.32.2`? That's a problem. Let me open an issue in the Sway repo.
