### ISSUE TITLE
Add the Rust version we use into the README

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#351]
### Motivation

In [CI](https://github.com/FuelLabs/sway-applications/blob/a8e081ef8bc77556ca94103965836cc195b2160b/.github/workflows/ci.yml#L17) we specify a Rust version; however, it is not stated in the [README](https://github.com/FuelLabs/sway-applications#running-a-project).

Add the version from CI into the README.

**Comment by x86Cow** [comment]
I am willing to fix this issue. This is my first I am contributing to, where should the version be in the readme? I did not see other versions of dependencies in the readme while I scrolled through. Thanks!

**Comment by Braqzen** [comment]
> I am willing to fix this issue. This is my first I am contributing to, where should the version be in the readme? I did not see other versions of dependencies in the readme while I scrolled through. Thanks!

In the note after `fuel-core`. Click the hyperlink in the description and look at the bottom of the page.
