### ISSUE TITLE
Configuration-time constants

### ISSUE THREAD

**Issue by supiket** [FuelLabs/sway-applications#375]
### Motivation

New configuration-time constants (https://github.com/FuelLabs/sway/pull/3536) will require reworking the currently used `Forc.toml` configuration-time constants across applications and allow resolving some `TODO`s.

Blocked by https://github.com/FuelLabs/sway/issues/3679 since `forc fmt --check` in the CI is currently resulting in an error.

**Comment by Braqzen** [comment]
Noting that following the issues it would appear that the feature for using non-literal config-time constants has been implemented; however, as of `forc 0.35.0` that is not the case.

**Comment by Braqzen** [comment]
Both issues seem to have been resolved although I'm uncertain about what we can do with the first link given that I've found something to not work when it was supposed to because of lack of support elsewhere.

Either way, [here](https://github.com/FuelLabs/sway/pull/4105) is the PR which was merged and released for `forc 0.35.2`. 
Removing `blocked`.

**Comment by bingcicle** [comment]
FYI: Config time constants as they are will be deprecated soon - details in this accompanying issue and comment [here](https://github.com/FuelLabs/sway/issues/3681#issuecomment-1461569540), but from the developer's POV, declaring the `[constants]` table will not be supported anymore, while `[contract-dependencies]` will still work as before but will use a different name than `ConfigTimeConstant` in the backend.

These changes aren't live yet on the current versions, so there's no need to deprecate usage yet - will comment here again once a PR is merged to master.

**Comment by bingcicle** [comment]
PR https://github.com/FuelLabs/sway/pull/4298 has been merged

**Comment by Braqzen** [comment]
> PR [FuelLabs/sway#4298](https://github.com/FuelLabs/sway/pull/4298) has been merged

Cool, once the SDK releases `Bytes` support I can bump my PRs with that support too.

**Comment by bitzoic** [comment]
This issue has been resolved in the bumping of apps
