### ISSUE TITLE
Code Quality for app tests (assets)

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#391]
### Motivation

The following applications have a `tests/artifacts/asset` which the SDK has made redundant a while ago therefore it can be removed and replaced with functionality from the SDK e.g. the [OTC](https://github.com/FuelLabs/sway-applications/blob/0132a8056a21babe810851b49f6630b68558dfd1/OTC-swap-predicate/project/swap-predicate/tests/utils/mod.rs#L21-L35) or something similar

- fundraiser
- fractional-NFT
- escrow
- english-auction
- DAO

**Comment by bitzoic** [comment]
This has been resolved
