### ISSUE TITLE
Change the `-` to `*` in the `.template` `interface.sw` file

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#392]
### Motivation

Lines [8](https://github.com/FuelLabs/sway-applications/blob/0132a8056a21babe810851b49f6630b68558dfd1/.template/project/template-contract/src/interface.sw#L8) & [12](https://github.com/FuelLabs/sway-applications/blob/0132a8056a21babe810851b49f6630b68558dfd1/.template/project/template-contract/src/interface.sw#L12) use a `-` for a bullet point.

Change them to `*`.

Reasoning: there is no visual reason to do this except to standardise the repository. In terms of work done, the `# Revert` section tends to have more points than the number of parameters for a function (in `# Arguments`) therefore it's less work to switch everything to use `*` in another PR.

**Comment by haadfida** [comment]
may I work on this?

**Comment by Braqzen** [comment]
> may I work on this?

Sure! I'll assign you.
