### ISSUE TITLE
Airdrop: interface bullet point style

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#419]
### Motivation

The [`interface of the .template`](https://github.com/FuelLabs/sway-applications/blob/0132a4a89bb0f9c1a5d016db609adead87c43626/.template/project/template-contract/src/interface.sw#L8) uses a `*` before each parameter and a `:` after it.

Update the interface in the application to follow the same style.

**Comment by bitzoic** [comment]
This has been resolved by https://github.com/FuelLabs/sway-applications/pull/720
