### ISSUE TITLE
Escrow: outdated comment in harness.rs

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#441]
### Motivation

The escrow has a comment stating that an [array should be changed to a vector](https://github.com/FuelLabs/sway-applications/blob/0132a4a89bb0f9c1a5d016db609adead87c43626/escrow/project/escrow-contract/tests/harness.rs#L4).

The contract seems to use vectors so that comment is likely invalid. Remove it.

**Comment by K1-R1** [comment]
Closed as of #677
