### ISSUE TITLE
Fundraiser: harness.rs has outdated comments

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#445]
### Motivation

All of the comments [here](https://github.com/FuelLabs/sway-applications/blob/0132a4a89bb0f9c1a5d016db609adead87c43626/fundraiser/project/fundraiser-contract/tests/harness.rs#L1-L11) are outdated / implemented. Remove them.

**Comment by K1-R1** [comment]
Closed as of #678
