### ISSUE TITLE
Oracle: change the type of `price` in `storage`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#448]
### Motivation

The `Option` type is supported by the SDK. 
Change the type to be an option containing a u64 [here](https://github.com/FuelLabs/sway-applications/blob/0132a4a89bb0f9c1a5d016db609adead87c43626/oracle/project/oracle-contract/src/main.sw#L17-L18). 
Adjust contract and tests.

**Comment by Kirito-Excalibur** [comment]
Can you explain what do you mean by `option` type?

**Comment by Braqzen** [comment]
> Can you explain what do you mean by `option` type?

The [`Option`](https://fuellabs.github.io/sway/master/std/option/enum.Option.html) type is an enum which represents two variants. A variant which is the lack of a value and the alternative is a variant which contains some value.

You can see some usage in a variety of contracts; however, [here](https://github.com/FuelLabs/sway-applications/blob/765f79a07d0c8d772a104087aba4e01e653820be/escrow/project/escrow-contract/src/main.sw#L47) is one concrete example. If you search for the `Option` type in that file it will show you how to use it.

The value returned from the getter should be an option too, this means tests will need to be adjusted.
