### ISSUE TITLE
Bump Repo

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#471]
### Motivation

The apps are a few versions behind because the last bump was 3-4 weeks ago.

The latest versions at the time of writing are

- SDK: `0.39.0`
- forc: `0.37.0`
- core: `0.17.8`

Apps

- [x] #623 
- [x] #473
- [x] #474
- [x] #639 
- [x] #625 
- [x] #477
- [x] #628 
- [x] #479
- [x] #480
- [x] #481
- [x] #482
- [x] #483
- [x] #627 
- [x] #485
- [x] #564

**Comment by bitzoic** [comment]
Closing in favor of https://github.com/FuelLabs/sway-applications/issues/732
