### ISSUE TITLE
Add information about the fuel-toolchain.toml files

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/sway-applications#498]
We should inform developers how we manage the dependency versions with the fuel-toolchain.toml files.  This will also inform them which versions they will need in order to run each app.

**Comment by Braqzen** [comment]
> We should inform developers how we manage the dependency versions with the fuel-toolchain.toml files. This will also inform them which versions they will need in order to run each app.

It's fine to mention the toolchain but not really which versions they need because the pins will automatically do things for us.
