### ISSUE TITLE
ui scaffolding `Core` system

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#499]
### Motivation

Update the scaffold to move the `hooks` and `utils` into a new directory under `src/systems/Core` and add a new `src/systems/Core/components` directory too.

The structure should be similar to (add whatever files are needed in addition):

```sh
src
└── systems
    └── Core
        ├── components
        │   └── index.tsx
        ├── hooks
        │   └── index.ts
        ├── index.tsx
        └── utils
            └── index.ts
```

The `index.tsx` above `utils` should contain

```js
export * from "./components";
export * from "./hooks";
export * from "./utils";
```

**Comment by supiket** [comment]
The tool is being moved to its separate repo atm and once it is distributed, it will most likely be deleted from `sway-applications`
