### ISSUE TITLE
AMM: implement the Indexer

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#505]
### Motivation

The AMM should implement the [indexer](https://github.com/FuelLabs/fuel-indexer) to keep track of:

- When a new pool is created and what that pool consists of / who created it
- When a deposit / withdraw is made, by who and what the deposit consists of
- Adding / removing liquidity, by who, when it occurred, what the asset consists of
- Swaps, by who, when, assets, how much

Each of these should probably be its own branch / feature.

**Comment by bitzoic** [comment]
Closing to consolidate to https://github.com/FuelLabs/sway-applications/issues/605
