### ISSUE TITLE
NFT: Missing test

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#526]
### Motivation

The `abi` for `Supply` contains a `set_max_supply()` which is not inside the `/tests/functions` directory.
Write a test to set the supply and check that the [event](https://github.com/FuelLabs/sway-libs/blob/55a1a3d5d0fcce55997dc31ce18369154088fa23/libs/nft/src/extensions/supply/supply.sw#L40) has been correctly emitted.

It is used as part of the `constructor` but we shouldn't couple tests that way.

**Comment by bitzoic** [comment]
It should be noted that this function can only be called *before* the constructor is called. Since the constructor sets the maximum supply and locks it, the use of this function does not impact the contract in any way. This function is included as it is part of the NFT library's abi for supply.

**Comment by bitzoic** [comment]
Closing as this has been removed with the introduction of native assets https://github.com/FuelLabs/sway-applications/pull/747
