### ISSUE TITLE
Canvas Smart Contract

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#561]
Contract should contain at least the following functionality:

- Fixed size canvas
  - Clearing all the slots would be expensive so once the canvas is created we cannot create a new one unless we perform some indexing up to the maximum `u64` size to create a few canvases per contract. Better to stick with a single canvas for now.
  - Index pixels by a `u64` for ease of use
- Each pixel is represented by some colour format e.g. rgb
- Getter to return a pixel colour
- Setter to set a pixel colour
- Initial implementation does not need to require a time delay between each placement
- Getter to return the maximum canvas size

**Comment by bitzoic** [comment]
Closing to consolidate to just https://github.com/FuelLabs/sway-applications/issues/559
