### ISSUE TITLE
AMM: Implement the indexer

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#606]
### Indexer Guideline

The AMM consists of two contracts therefore we can separate the indexer into two modules.

Each index should contain functions in the format  `index_<event_name>`.

E.g.

```rust
#[indexer(manifest = "<path/to/file/amm.manifest.yaml>")]
mod amm_index {
    fn index_register_pool_event(event: RegisterPoolEvent, block: BlockData) { ... }
}

#[indexer(manifest = "<path/to/file/amm-exchange.manifest.yaml>")]
mod amm_exchange_index {
    fn index_add_liquidity_event(event: AddLiquidityEvent, block: BlockData) { ... }

   // more events
}
```

Each type in graphql should have a `required` field.

Certain event fields would benefit from the `@indexed` directive.

- AMM
  - `RegisterPoolEvent`
    - asset_pair
    - pool
- Exchange
  - `AddLiquidityEvent`
    - added_assets
  - `DepositEvent`
    - deposited_asset
  - `RemoveLiquidityEvent`
    - removed_reserve
  - `SwapEvent`
    - input
    - output
  - `WithdrawEvent`
    - withdrawn_asset

From the `BlockData` we should retrieve the block height and add it to each event so that we have a measure of time for when the event took place.

**Comment by bitzoic** [comment]
Closing in favor of https://github.com/FuelLabs/sway-applications/issues/605
