### ISSUE TITLE
Multisig: Implement the indexer

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#607]
### Indexer Guideline

There should be a single wasm module which contains multiple functions, 1 per event. The fn name may follow the pattern `index_<event_name>`.

E.g.

```rust
#[indexer(manifest = "<path/to/file/multisig.manifest.yaml>")]
mod multisig_index {
    fn index_cancel_event(event: CancelEvent, block: BlockData) { ... }

    fn index_execute_event(event: ExecutedEvent, block: BlockData) { ... }

    // more events below
}
```

Each type in graphql should have a required field.

Certain event fields would benefit from the `@indexed` directive.

- `CancelEvent`
  - user
- `ExecutedEvent`
  - to
  - value
- `SetWeightEvent`
  - user
- `TransferEvent`
  - asset_id
  - to
  - value

From the `BlockData` we should retrieve the block height and add it to each event so that we have a measure of time for when the event took place.

**Comment by bitzoic** [comment]
Closing in favor of https://github.com/FuelLabs/sway-applications/issues/605
