### ISSUE TITLE
English Auction: Implement the indexer

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#608]
### Indexer Guideline

There should be a single wasm module which contains multiple functions, 1 per event. The fn name may follow the pattern `index_<event_name>`.

E.g.

```rust
#[indexer(manifest = "<path/to/file/auction.manifest.yaml>")]
mod auction_index {
    fn index_bid_event(event: BidEvent, block: BlockData) { ... }

    fn index_cancel_auction_event(event: CancelAuctionEvent, block: BlockData) { ... }

    // more events below
}
```

Each type in graphql should have a required field.

Certain event fields would benefit from the `@indexed` directive.

- `BidEvent`
  - auction_id
  - user
- `CancelAuctionEvent`
  - auction_id
- `CreateAuctionEvent`
  - bid_asset
  - sell_asset
- `WithdrawEvent`
  - asset
  - auction_id
  - user

From the `BlockData` we should retrieve the block height and add it to each event so that we have a measure of time for when the event took place.

**Comment by bitzoic** [comment]
Closing in favor of https://github.com/FuelLabs/sway-applications/issues/605
