### ISSUE TITLE
Airdrop: Implement the indexer

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#609]
### Indexer Guideline

There should be a single wasm module which contains multiple functions, 1 per event. The fn name may follow the pattern `index_<event_name>`.

E.g.

```rust
#[indexer(manifest = "<path/to/file/airdrop.manifest.yaml>")]
mod airdrop_index {
    fn index_claim_event(event: ClaimEvent, block: BlockData) { ... }

    fn index_clawback_event(event: ClawbackEvent, block: BlockData) { ... }

    // more events below
}
```

Each type in graphql should have a required field.

Certain event fields would benefit from the `@indexed` directive.

- `ClaimEvent`
  - amount
  - claimer
  - to

From the `BlockData` we should retrieve the block height and add it to each event so that we have a measure of time for when the event took place.

**Comment by bitzoic** [comment]
Closing in favor of https://github.com/FuelLabs/sway-applications/issues/605
