### ISSUE TITLE
Fundraiser Application

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#64]
### Application Description

Sway smart contract similar to an escrow, also has a user interface.

Users can deposit a specified asset to the contract within a specified time range.
1. If the total sum pledged meets the goal then the author can claim the funds and automatically close the contract 
2. Otherwise everyone can withdraw their pledge

### Motivation

It has a similar application to an Escrow and it is a viable real world use case via decentralized conditional funding.
A sway application should be created to demonstrate its usage.

### Features

- [x] #65
- [ ] #66

### Additional context

_Tuturu_

**Comment by bitzoic** [comment]
Closing in favor of https://github.com/FuelLabs/sway-applications/issues/66
