### ISSUE TITLE
Airdrop: add documentation for `mint_to()` to the SPECIFICATION

### ISSUE THREAD

**Issue by K1-R1** [FuelLabs/sway-applications#645]

**Comment by Braqzen** [comment]
The label for `Repo Misc` is more towards general upkeep such as the devops tool, CI, bumping apps etc. Basically anything that is pretty broad and doesn't really fit into a specific category that warrants a label - thus I'm removing the misc label

**Comment by bitzoic** [comment]
This has been resolved by https://github.com/FuelLabs/sway-applications/pull/760
