### ISSUE TITLE
NFT Auctions

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#68]
### Application Description

Related: #47 

Application which allows a user to specify the type of auction for their NFT sale.
This would allow the user to choose between a dutch auction, english auction and a blind auction.

### Motivation

An NFT can have a value set inside of it for a sale and that value may be static.

Alternatively, an auction mechanism may be used to allow the market to choose the price for the NFT (barring some restrictions such as a minimum and maximum price).

### Features

- [ ] #69
- [x] #70
- [ ] #74 
- [ ] #71

### Additional context

cc @bitzoic

**Comment by bitzoic** [comment]
Closing as this is satisfied by the current English Auction design
