### ISSUE TITLE
Update and reintroduce `fractional-NFT`

### ISSUE THREAD

**Issue by K1-R1** [FuelLabs/sway-applications#714]
The `fractional-NFT` application was temporarily archived awating the release of the [Sway multi-token standard](https://github.com/FuelLabs/rfcs/pull/17).  Once this standard has been finalised and the version of `forc` that supports this standard is released; the `fractional-NFT` app should be updated and reintroduced.

**Comment by bitzoic** [comment]
This has been unblocked with the introduction of the SRC-6 vault standard https://github.com/FuelLabs/sway-standards/pull/24
