### ISSUE TITLE
<title>I want to use Python to bridge Sepolia's ETH across chains to Fuel

### ISSUE THREAD

**Issue by WeirdoPunk** [FuelLabs/sway-applications#787]
### Motivation

I want to use Python to bridge Sepolia's ETH across chains to Fuel

**Comment by K1-R1** [comment]
Hi @WeirdoPunk, the purpose of this repository is to contain end-to-end applications that are written in Sway in order to demonstrate what can be built.
I'd recommend asking this question or our forum...
