### ISSUE TITLE
Setup Nightly Tests Using Latest Version of forc and libs

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway-applications#796]
### Motivation

Now that breaking changes will be limited in future versions of Sway and new implementations designed to be backwards compatible, there should be tests run nightly using the latest version of forc, sway-standards, and sway-libs. 

Should anything break, there should be a report made such that any issues can be addressed.

**Comment by K1-R1** [comment]
Can this be closed as Sway-apps is under Devrel ownership?

**Comment by bitzoic** [comment]
Closing as part of Devrel
